# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-07 13:14
from __future__ import unicode_literals

from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0233_add_credit_value_to_program_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtype',
            name='logo_image',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide an image file with transparent background', null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='media/program_types/logo_images/{instance.name:.40slug}{ext}')),
        ),
    ]
